name: Python CI
on:
  push:
    branches: [ main ]
  jobs:
    name: Build
    strategy:
      matrix:
        python-version: [3.11.x, 3.12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        uses: python py/test_money.py -v
        shell: bash